# Generated by Django 4.2.6 on 2023-10-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
