# Generated by Django 4.2.6 on 2023-11-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
