# Generated by Django 4.2.6 on 2023-11-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_profile_user_alter_user_profile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='address',
            field=models.CharField(max_length=20),
        ),
    ]
