# Generated by Django 4.2.6 on 2023-11-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='images/'),
        ),
    ]
