# Generated by Django 4.2.6 on 2023-11-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
