# Generated by Django 4.2.6 on 2023-11-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
