# Generated by Django 4.2.6 on 2023-11-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_profile_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='address_line_2',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
    ]
