# Generated by Django 4.2.6 on 2023-11-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_address_user_profile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
