# Generated by Django 4.2.6 on 2023-10-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=True, max_length=50, null=True)),
                ('image', models.ImageField(default=True, upload_to='images')),
                ('category_description', models.CharField(blank=True, default=True, max_length=50, null=True)),
                ('in_stock', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'name',
            },
        ),
    ]
