# Generated by Django 4.2.6 on 2023-10-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_category_in_stock_category_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
