# Generated by Django 4.2.6 on 2023-11-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_product_variant_image_id_product_variant_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutipleimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
