# Generated by Django 4.2.6 on 2023-11-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_mutipleimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], default='None', max_length=10),
        ),
    ]
