# Generated by Django 4.2.6 on 2023-10-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_brand_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_description',
        ),
    ]
