# Generated by Django 4.2.6 on 2023-11-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_image', models.ImageField(blank=True, null=True, upload_to='banner_images')),
                ('fb_images', models.ImageField(blank=True, null=True, upload_to='fb_images')),
                ('partners_images', models.ImageField(blank=True, null=True, upload_to='fb_images')),
            ],
        ),
    ]
