# Generated by Django 4.2.6 on 2023-11-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_mutipleimage_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MutipleImage',
        ),
    ]
