# Generated by Django 4.2.6 on 2023-10-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
