# Generated by Django 4.2.6 on 2023-11-08 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_mutipleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutipleimage',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.product_variant'),
        ),
    ]
