# Generated by Django 4.2.6 on 2023-11-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_mutipleimage_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutipleimage',
            name='product',
        ),
    ]
