# Generated by Django 4.2.6 on 2023-10-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_img/'),
        ),
    ]
