# Generated by Django 4.2.6 on 2023-11-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_rename_mutipleimage_multipleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='size',
        ),
        migrations.AddField(
            model_name='product_variant',
            name='colors',
            field=models.ManyToManyField(blank=True, to='items.color'),
        ),
        migrations.AddField(
            model_name='product_variant',
            name='size',
            field=models.ManyToManyField(blank=True, to='items.size'),
        ),
    ]
