# Generated by Django 4.2.6 on 2023-11-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_remove_product_variant_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleimage',
            name='title',
        ),
    ]
