# Generated by Django 4.2.6 on 2023-11-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_remove_multipleimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='images',
            field=models.ImageField(blank=True, default=2, upload_to='variantproduct_images'),
            preserve_default=False,
        ),
    ]
