# Generated by Django 4.2.6 on 2023-11-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_alter_banner_partners_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='partners_images',
            field=models.ImageField(blank=True, null=True, upload_to='partners_images'),
        ),
    ]
