# Generated by Django 4.2.6 on 2023-10-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_rename_product_variant_productimage_pro_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
    ]
