# Generated by Django 4.2.6 on 2023-10-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_rename_image_productimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
