# Generated by Django 4.2.6 on 2023-10-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_alter_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
    ]
