# Generated by Django 4.2.6 on 2023-11-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_remove_product_variant_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='image_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
