# Generated by Django 4.2.6 on 2023-10-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_alter_category_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.CharField(blank=True, default=True, max_length=30, null=True),
        ),
    ]
