# Generated by Django 4.2.6 on 2023-11-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_product_variant_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='size',
        ),
        migrations.AddField(
            model_name='product_variant',
            name='colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.color'),
        ),
        migrations.AddField(
            model_name='product_variant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.size'),
        ),
    ]
