# Generated by Django 4.2.6 on 2023-10-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_alter_category_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
