# Generated by Django 4.2.6 on 2023-11-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_single_product_cartitem_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
