# Generated by Django 4.2.6 on 2023-11-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_banner_partners_images'),
        ('cart', '0009_cart_cart_product_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_product',
            old_name='products',
            new_name='product_variant',
        ),
        migrations.AddField(
            model_name='cart_product',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.products'),
        ),
        migrations.AlterField(
            model_name='cart_product',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
