# Generated by Django 4.2.3 on 2023-11-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_products_cart_product_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
