# Generated by Django 4.2.6 on 2023-11-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=True, max_length=250),
            preserve_default=False,
        ),
    ]
