# Generated by Django 4.2.6 on 2023-11-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_cart_product_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
